# Generated by Django 4.1.5 on 2023-01-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("address", models.CharField(max_length=140)),
                ("tel", models.CharField(max_length=140)),
                ("lat", models.DecimalField(decimal_places=9, max_digits=10)),
                ("lng", models.DecimalField(decimal_places=9, max_digits=10)),
                (
                    "image",
                    models.FileField(blank=True, default="", upload_to="shop_image"),
                ),
            ],
        ),
    ]
