# Generated by Django 4.1.5 on 2023-01-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name="shop",
            name="lat",
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name="shop",
            name="lng",
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AddField(
            model_name="shop",
            name="category_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="maps.category",
            ),
        ),
    ]
