# Generated by Django 4.1.5 on 2023-01-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_shop_unique data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borough", models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name="shop",
            name="borough_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="maps.borough",
            ),
        ),
    ]
