# Generated by Django 4.1.1 on 2022-10-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycles", "0009_alter_photo_trash_name_alter_recycle_category_and_more"),
        ("users", "0002_alter_fav_favs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favs",
            field=models.ManyToManyField(
                blank=True, related_name="favs", to="recycles.recycle"
            ),
        ),
        migrations.DeleteModel(
            name="Fav",
        ),
    ]
