# Generated by Django 4.1.2 on 2022-10-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
