# Generated by Django 4.1.1 on 2022-09-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_nickname_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
