# Generated by Django 4.1.2 on 2022-11-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0022_challengeapply_alter_challenge_member"),
        ("users", "0006_alter_profile_has_challenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="has_challenge",
            field=models.ManyToManyField(default="", to="challenges.challengeapply"),
        ),
    ]
