# Generated by Django 4.1.2 on 2022-11-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0028_challengeapply_challenge_member"),
        ("users", "0008_alter_profile_has_challenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="has_challenge",
            field=models.ManyToManyField(
                blank=True, default="", to="challenges.challengeapply"
            ),
        ),
    ]
