# Generated by Django 4.1.2 on 2022-11-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_profile_has_challenge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="has_challenge",
        ),
    ]
