# Generated by Django 4.1.2 on 2022-11-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_profile_has_challenge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="nickname",
            new_name="nickname_id",
        ),
    ]
