# Generated by Django 4.2.1 on 2023-07-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0044_alter_challenge_member'),
        ('users', '0013_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_challenges',
            field=models.ManyToManyField(to='challenges.challenge'),
        ),
    ]
