# Generated by Django 4.2.1 on 2023-07-11 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0046_rename_profile_id_challengeapply_member_id_and_more'),
        ('users', '0014_profile_my_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_challenges',
            field=models.ManyToManyField(through='challenges.ChallengeApply', to='challenges.challenge'),
        ),
    ]
