# Generated by Django 4.2.1 on 2023-07-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0045_remove_challengeapply_member_id_and_more'),
        ('users', '0014_profile_my_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_challenges',
            field=models.ManyToManyField(through='challenges.ChallengeApply', to='challenges.challenge'),
        ),
    ]
