# Generated by Django 4.2.1 on 2023-08-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0053_remove_challengeapply_certification_and_more'),
        ('users', '0016_remove_profile_nickname_remove_user_nickname_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_certifications',
            field=models.ManyToManyField(blank=True, to='challenges.challengecertification'),
        ),
    ]
