# Generated by Django 4.2.1 on 2023-09-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_my_certifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='my_certifications',
        ),
    ]
