# Generated by Django 4.2.1 on 2023-09-04 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_profile_my_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
