# Generated by Django 4.2.1 on 2023-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0061_challenge_certifications'),
        ('users', '0019_alter_profile_nickname_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_certifications',
            field=models.ManyToManyField(related_name='profiles', through='challenges.ChallengeCertification', to='challenges.challenge'),
        ),
    ]
