# Generated by Django 4.1 on 2022-09-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recycles", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="recycle",
            new_name="Recycles",
        ),
    ]
