# Generated by Django 4.1 on 2022-09-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recycles", "0002_rename_recycle_recycles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recycles",
            name="category",
        ),
    ]
