# Generated by Django 4.1 on 2022-09-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycles", "0004_recycle_delete_recycles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("furniture", "가구"),
                            ("household goods", "생활용품"),
                            ("book", "도서"),
                            ("home appliances", "가전제품"),
                            ("cosmetics", "화장품"),
                            ("fashion", "패션"),
                            ("kitchenware", "주방용품"),
                            ("food", "식품"),
                            ("container/packaging", "용기/포장재"),
                            ("glass", "유리"),
                            ("vinyl", "비닐 OTHER"),
                            ("plastic", "플라스틱 OTHER"),
                            ("rubber", "고무"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "category_photo",
                    models.FileField(
                        upload_to="category", verbose_name="category_photo"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                ("trash_photo", models.FileField(upload_to="trash")),
                (
                    "trash_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recycles.recycle",
                        verbose_name="trash name",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="recycle",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recycles.category",
            ),
        ),
    ]
