# Generated by Django 4.1 on 2022-09-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycles", "0005_category_photo_alter_recycle_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(
                choices=[
                    ("furniture", "가구"),
                    ("household goods", "생활용품"),
                    ("book", "도서"),
                    ("home appliances", "가전제품"),
                    ("cosmetics", "화장품"),
                    ("fashion", "패션"),
                    ("kitchenware", "주방용품"),
                    ("food", "식품"),
                    ("container/packaging", "용기/포장재"),
                    ("glass", "유리"),
                    ("vinyl", "비닐 OTHER"),
                    ("plastic", "플라스틱 OTHER"),
                    ("rubber", "고무"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="modified",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="modified",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="recycle",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="recycle",
            name="modified",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
