# Generated by Django 4.1 on 2022-09-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycles", "0006_alter_category_category_alter_category_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recycle",
            name="category_photo",
            field=models.FileField(
                null=True, upload_to="category", verbose_name="category_photo"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="trash_photo",
            field=models.FileField(upload_to="recycle"),
        ),
        migrations.AlterField(
            model_name="recycle",
            name="category",
            field=models.CharField(
                choices=[
                    ("furniture", "가구"),
                    ("household goods", "생활용품"),
                    ("book", "도서"),
                    ("home appliances", "가전제품"),
                    ("cosmetics", "화장품"),
                    ("fashion", "패션"),
                    ("kitchenware", "주방용품"),
                    ("food", "식품"),
                    ("container/packaging", "용기/포장재"),
                    ("glass", "유리"),
                    ("vinyl", "비닐 OTHER"),
                    ("plastic", "플라스틱 OTHER"),
                    ("rubber", "고무"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="recycle",
            name="how_to_recyle",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recycle",
            name="tip",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
