# Generated by Django 4.1 on 2022-09-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycles", "0007_recycle_category_photo_alter_photo_trash_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recycle",
            name="category_photo",
            field=models.FileField(
                default=True, upload_to="category", verbose_name="category_photo"
            ),
        ),
    ]
