# Generated by Django 4.1.2 on 2022-10-20 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("modified", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(default="", max_length=140)),
                (
                    "title_banner",
                    models.ImageField(default="", upload_to="title_banner"),
                ),
                ("challenge_summery", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_day", models.TimeField()),
                ("end_day", models.TimeField()),
                (
                    "certification_success_photo_example",
                    models.ImageField(
                        upload_to="success_photo_ex", verbose_name="success photo"
                    ),
                ),
                (
                    "certification_fail_photo_example",
                    models.ImageField(
                        upload_to="success_fail_ex", verbose_name="fail photo"
                    ),
                ),
                ("certification_notice", models.TextField(blank=True)),
                (
                    "members",
                    models.ManyToManyField(
                        default="",
                        related_name="challenge_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
