# Generated by Django 4.1.2 on 2022-10-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="certification_fail_photo_example",
            field=models.ImageField(
                blank=True, upload_to="success_fail_ex", verbose_name="fail photo"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="certification_success_photo_example",
            field=models.ImageField(
                blank=True, upload_to="success_photo_ex", verbose_name="success photo"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title_banner",
            field=models.ImageField(blank=True, default="", upload_to="title_banner"),
        ),
    ]
