# Generated by Django 4.1.2 on 2022-10-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0002_alter_challenge_certification_fail_photo_example_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenge",
            old_name="description",
            new_name="challenge_description",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="end_day",
        ),
        migrations.AddField(
            model_name="challenge",
            name="duration",
            field=models.CharField(
                choices=[
                    ("1time", "주 1회"),
                    ("2times", "주 2회"),
                    ("3times", "주 3회"),
                    ("4times", "주 4회"),
                    ("5times", "주 5회"),
                    ("6times", "주 6회"),
                    ("7times", "매일"),
                    ("weekday", "평일 매일"),
                    ("weekend", "주말"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("1time", "주 1회"),
                    ("2times", "주 2회"),
                    ("3times", "주 3회"),
                    ("4times", "주 4회"),
                    ("5times", "주 5회"),
                    ("6times", "주 6회"),
                    ("7times", "매일"),
                    ("weekday", "평일 매일"),
                    ("weekend", "주말"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="start_day",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="ChallengeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(null=True)),
                ("comment", models.CharField(default="", max_length=100)),
                (
                    "challenge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="challenges.challenge",
                        verbose_name="review",
                    ),
                ),
            ],
        ),
    ]
