# Generated by Django 4.1.2 on 2022-10-27 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "challenges",
            "0003_rename_description_challenge_challenge_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="duration",
            field=models.CharField(
                choices=[
                    ("1week", "1주 동안"),
                    ("2weeks", "2주 동안"),
                    ("3week", "3주 동안"),
                    ("4week", "4주 동안"),
                    ("5week", "5주 동안"),
                    ("6week", "6주 동안"),
                    ("7week", "7주 동안"),
                    ("8week", "8주 동안"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
