# Generated by Django 4.1.2 on 2022-10-31 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0004_alter_challenge_duration_alter_challenge_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="members",
        ),
        migrations.CreateModel(
            name="ChallengeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member",
                        to="challenges.challenge",
                    ),
                ),
            ],
        ),
    ]
