# Generated by Django 4.1.2 on 2022-11-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile"),
        ("challenges", "0005_remove_challenge_members_challengemember"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="member",
            field=models.ManyToManyField(related_name="challenge", to="users.profile"),
        ),
        migrations.DeleteModel(
            name="ChallengeMember",
        ),
    ]
