# Generated by Django 4.1.2 on 2022-11-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile"),
        ("challenges", "0006_challenge_member_delete_challengemember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="member",
            field=models.ManyToManyField(related_name="member", to="users.profile"),
        ),
    ]
