# Generated by Django 4.1.2 on 2022-11-04 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0012_alter_challenge_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="member",
        ),
        migrations.AlterField(
            model_name="challengemember",
            name="member",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
