# Generated by Django 4.1.2 on 2022-11-04 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0013_remove_challenge_member_alter_challengemember_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="max_member",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(20)]
            ),
        ),
    ]
