# Generated by Django 4.1.2 on 2022-11-04 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0014_challenge_max_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengemember",
            name="member",
        ),
        migrations.AddField(
            model_name="challengemember",
            name="member",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
