# Generated by Django 4.1.2 on 2022-11-04 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0015_remove_challengemember_member_challengemember_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="member",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="ChallengeMember",
        ),
    ]
