# Generated by Django 4.1.2 on 2022-11-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0016_challenge_member_delete_challengemember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="certification_fail_photo_example",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="success_fail_ex",
                verbose_name="fail photo",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="certification_success_photo_example",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="success_photo_ex",
                verbose_name="success photo",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title_banner",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="title_banner"
            ),
        ),
    ]
