# Generated by Django 4.1.2 on 2022-11-07 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "challenges",
            "0017_alter_challenge_certification_fail_photo_example_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
    ]
