# Generated by Django 4.1.2 on 2022-11-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0019_alter_challenge_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="start_day",
            field=models.DateTimeField(null=True),
        ),
    ]
