# Generated by Django 4.1.2 on 2022-11-07 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0020_alter_challenge_start_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="member",
            field=models.ManyToManyField(
                blank=True, related_name="member", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
