# Generated by Django 4.1.2 on 2022-11-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_has_challenge"),
        ("challenges", "0021_alter_challenge_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeApply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "challenge_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenges.challenge",
                        verbose_name="challenge name",
                    ),
                ),
                (
                    "member_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                        verbose_name="member name",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="challenge",
            name="member",
            field=models.ManyToManyField(
                blank=True, related_name="member", to="challenges.challengeapply"
            ),
        ),
    ]
