# Generated by Django 4.1.2 on 2022-11-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0022_challengeapply_alter_challenge_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="member",
        ),
    ]
