# Generated by Django 4.1.2 on 2022-11-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0023_remove_challenge_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="member",
            field=models.ManyToManyField(
                blank=True, related_name="member", to="challenges.challengeapply"
            ),
        ),
    ]
