# Generated by Django 4.1.2 on 2022-11-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_profile_has_challenge"),
        ("challenges", "0026_remove_challenge_member"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChallengeApply",
        ),
    ]
