# Generated by Django 4.1.2 on 2022-11-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0028_challengeapply_challenge_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="member",
        ),
    ]
