# Generated by Django 4.1.2 on 2022-11-10 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_profile_has_challenge"),
        ("challenges", "0029_remove_challenge_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengeapply",
            name="challenge_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="challenges.challenge",
                verbose_name="challenge name",
            ),
        ),
        migrations.AlterField(
            model_name="challengeapply",
            name="member_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
                verbose_name="member name",
            ),
        ),
    ]
