# Generated by Django 4.1.2 on 2022-11-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0031_alter_challengeapply_challenge_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challengeapply",
            old_name="challenge_name",
            new_name="challenge_id",
        ),
        migrations.RenameField(
            model_name="challengeapply",
            old_name="member_name",
            new_name="member_id",
        ),
    ]
