# Generated by Django 4.1.2 on 2022-11-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0032_rename_challenge_name_challengeapply_challenge_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="number_of_applied_member",
            field=models.IntegerField(default=0),
        ),
    ]
