# Generated by Django 4.1.2 on 2022-11-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0033_challenge_number_of_applied_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="number_of_applied_member",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
