# Generated by Django 4.1.2 on 2022-12-22 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0034_alter_challenge_number_of_applied_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="duration",
            field=models.CharField(
                choices=[("1week", 1), ("2weeks", 2), ("3weeks", 3), ("4weeks", 4)],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("1time", 1),
                    ("2times", 2),
                    ("3times", 3),
                    ("4times", 4),
                    ("5times", 5),
                    ("6times", 6),
                    ("7times", 7),
                    ("weekday", 5),
                    ("weekend", 2),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="start_day",
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name="ChallengeCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification_date", models.DateTimeField(auto_now=True)),
                (
                    "certification_photo",
                    models.FileField(blank=True, default="", upload_to="certification"),
                ),
                ("certification_comment", models.CharField(blank=True, max_length=255)),
                (
                    "challenge_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenges.challenge",
                    ),
                ),
            ],
        ),
    ]
