# Generated by Django 4.1.2 on 2022-12-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0035_alter_challenge_duration_alter_challenge_frequency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="start_day",
            field=models.DateTimeField(null=True),
        ),
    ]
