# Generated by Django 4.1.2 on 2022-12-22 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_nickname_profile_nickname_id"),
        ("challenges", "0036_alter_challenge_start_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengecertification",
            name="challenge_Participant_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
