# Generated by Django 4.1.2 on 2022-12-23 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_nickname_profile_nickname_id"),
        ("challenges", "0036_alter_challenge_start_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengecertification",
            name="challenge_participant_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="challengecertification",
            name="challenge_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_certification_name",
                to="challenges.challenge",
            ),
        ),
    ]
