# Generated by Django 4.1.5 on 2023-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0037_challengecertification_challenge_participant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="duration",
            field=models.CharField(
                choices=[("1주 동안", 1), ("2주 동안", 2), ("3주 동안", 3), ("4주 동안", 4)],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("주 1일", 1),
                    ("주 2일", 2),
                    ("주 3일", 3),
                    ("주 4일", 4),
                    ("주 5일", 5),
                    ("주 6일", 6),
                    ("주 7일", 7),
                    ("평일 매일", 8),
                    ("주말 매일", 9),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="challengereview",
            name="challenge",
        ),
        migrations.AddField(
            model_name="challengereview",
            name="challenge",
            field=models.ManyToManyField(
                related_name="review", to="challenges.challenge", verbose_name="review"
            ),
        ),
    ]
