# Generated by Django 4.2.1 on 2023-06-26 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0038_alter_challenge_duration_alter_challenge_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='certification_fail_photo_example',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='certification_success_photo_example',
        ),
        migrations.CreateModel(
            name='CertificationExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_photo_example', models.ImageField(blank=True, null=True, upload_to='certi_photo_ex', verbose_name='certi photo')),
                ('SuccessOrFail', models.BooleanField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='challenges.challenge', verbose_name='challenge name')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='certification_photo_example',
            field=models.ManyToManyField(related_name='CertificationExample', to='challenges.certificationexample'),
        ),
    ]
