# Generated by Django 4.2.1 on 2023-06-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0039_remove_challenge_certification_fail_photo_example_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationexample',
            name='SuccessOrFail',
        ),
        migrations.RemoveField(
            model_name='certificationexample',
            name='certification_photo_example',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='certification_photo_example',
        ),
        migrations.AddField(
            model_name='certificationexample',
            name='failure_photo_example',
            field=models.ImageField(blank=True, null=True, upload_to='failure_photo_ex', verbose_name='failure photo'),
        ),
        migrations.AddField(
            model_name='certificationexample',
            name='success_photo_example',
            field=models.ImageField(blank=True, null=True, upload_to='success_photo_ex', verbose_name='success photo'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='failure_photo_example',
            field=models.ManyToManyField(related_name='certi_failure_example', to='challenges.certificationexample'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='success_photo_example',
            field=models.ManyToManyField(related_name='certi_success_photo', to='challenges.certificationexample'),
        ),
    ]
