# Generated by Django 4.2.1 on 2023-06-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0040_remove_certificationexample_successorfail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationexample',
            name='failure_photo_example',
        ),
        migrations.RemoveField(
            model_name='certificationexample',
            name='success_photo_example',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='failure_photo_example',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='success_photo_example',
        ),
        migrations.AddField(
            model_name='certificationexample',
            name='SuccessOrFail',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='certificationexample',
            name='certification_photo_example',
            field=models.ImageField(blank=True, null=True, upload_to='certi_photo_ex', verbose_name='certi photo'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='certification_photo_example',
            field=models.ManyToManyField(related_name='CertificationExample', to='challenges.certificationexample'),
        ),
    ]
