# Generated by Django 4.2.1 on 2023-06-30 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0041_remove_certificationexample_failure_photo_example_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='member',
            field=models.ManyToManyField(related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
