# Generated by Django 4.2.1 on 2023-06-30 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0042_challenge_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='member',
            field=models.ManyToManyField(null=True, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
