# Generated by Django 4.2.1 on 2023-07-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_active'),
        ('challenges', '0043_alter_challenge_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='member',
            field=models.ManyToManyField(related_name='challenges', through='challenges.ChallengeApply', to='users.profile'),
        ),
    ]
