# Generated by Django 4.2.1 on 2023-07-03 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_my_challenges'),
        ('challenges', '0044_alter_challenge_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeapply',
            name='member_id',
        ),
        migrations.AddField(
            model_name='challengeapply',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_name', to='users.profile', verbose_name='member name'),
        ),
    ]
