# Generated by Django 4.2.1 on 2023-07-06 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0045_remove_challengeapply_member_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeapply',
            old_name='profile_id',
            new_name='member_id',
        ),
        migrations.AlterField(
            model_name='challengecertification',
            name='challenge_participant_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
