# Generated by Django 4.2.1 on 2023-08-21 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0046_rename_profile_id_challengeapply_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengecertification',
            name='challenge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_certification_name', to='challenges.challengeapply'),
        ),
    ]
