# Generated by Django 4.2.1 on 2023-08-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0047_alter_challengecertification_challenge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengecertification',
            name='challenge_id',
        ),
        migrations.RemoveField(
            model_name='challengecertification',
            name='challenge_participant_id',
        ),
        migrations.RemoveField(
            model_name='challengecertification',
            name='id',
        ),
        migrations.AddField(
            model_name='challengeapply',
            name='certification',
            field=models.ManyToManyField(related_name='certification', to='challenges.challengecertification'),
        ),
        migrations.AddField(
            model_name='challengecertification',
            name='certification_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
