# Generated by Django 4.2.1 on 2023-08-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0048_remove_challengecertification_challenge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeapply',
            name='certification',
            field=models.ManyToManyField(to='challenges.challengecertification'),
        ),
    ]
