# Generated by Django 4.2.1 on 2023-08-31 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_profile_nickname_remove_user_nickname_id_and_more'),
        ('challenges', '0052_alter_challengeapply_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeapply',
            name='certification',
        ),
        migrations.AddField(
            model_name='challengecertification',
            name='challenge_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='applied_challenge', to='challenges.challenge', verbose_name='challenge name'),
        ),
        migrations.AddField(
            model_name='challengecertification',
            name='participant_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='users.profile', verbose_name='member name'),
        ),
        migrations.AlterField(
            model_name='challengecertification',
            name='certification_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
