# Generated by Django 4.2.1 on 2023-08-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0055_alter_challengeapply_challenge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengecertification',
            name='certification_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
