# Generated by Django 4.2.1 on 2023-09-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0058_alter_challengecertification_challenge_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengecertification',
            old_name='challenge_id',
            new_name='applied_id',
        ),
    ]
