# Generated by Django 4.2.1 on 2023-09-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0059_rename_challenge_id_challengecertification_applied_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengecertification',
            name='applied_id',
        ),
        migrations.AddField(
            model_name='challengecertification',
            name='challenge_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certification_challenge', to='challenges.challenge', verbose_name='challenge name'),
        ),
    ]
