# Generated by Django 4.2.1 on 2023-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0060_remove_challengecertification_applied_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='certifications',
            field=models.ManyToManyField(related_name='Certifications', to='challenges.challengecertification'),
        ),
    ]
