# Generated by Django 4.2.1 on 2023-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0061_challenge_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='certification_photo_example',
            field=models.ManyToManyField(null=True, related_name='CertificationExample', to='challenges.certificationexample'),
        ),
    ]
