# Generated by Django 4.2.1 on 2023-11-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_my_certifications'),
        ('challenges', '0063_alter_challenge_certification_photo_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailPhotoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fail_photo', models.ImageField(blank=True, null=True, upload_to='fail_photo_ex')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessPhotoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_photo', models.ImageField(blank=True, null=True, upload_to='success_photo_ex')),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='certification_photo_example',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='member',
            field=models.ManyToManyField(through='challenges.ChallengeApply', to='users.profile'),
        ),
        migrations.DeleteModel(
            name='CertificationExample',
        ),
        migrations.AddField(
            model_name='successphotoexample',
            name='challenge_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_success_photo', to='challenges.challenge', verbose_name='challenge name'),
        ),
        migrations.AddField(
            model_name='failphotoexample',
            name='challenge_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_fail_photo', to='challenges.challenge', verbose_name='challenge name'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='fail_photo_example',
            field=models.ManyToManyField(default='', to='challenges.failphotoexample'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='success_photo_example',
            field=models.ManyToManyField(default='', to='challenges.successphotoexample'),
        ),
    ]
