# Generated by Django 4.2.1 on 2023-11-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0064_failphotoexample_successphotoexample_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_summery',
            new_name='summery',
        ),
        migrations.AddField(
            model_name='challenge',
            name='certifications_end_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='challenge',
            name='certifications_start_time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
