# Generated by Django 4.2.1 on 2023-11-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0065_rename_challenge_description_challenge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='start_day',
            field=models.DateField(null=True),
        ),
    ]
