# Generated by Django 4.2.1 on 2023-11-20 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_my_certifications'),
        ('challenges', '0066_alter_challenge_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='failphotoexample',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fail_photo_owner', to='users.profile', verbose_name='member name'),
        ),
        migrations.AddField(
            model_name='successphotoexample',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='success_photo_owner', to='users.profile', verbose_name='member name'),
        ),
    ]
