# Generated by Django 4.2.1 on 2023-11-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_my_certifications'),
        ('challenges', '0067_failphotoexample_owner_successphotoexample_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successphotoexample',
            name='owner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success_photo_owner', to='users.profile', verbose_name='member name'),
        ),
    ]
